import os

PORTAL_TEST_PASSWORD = os.getenv("PORTAL_TEST_PASSWORD", "123456")
PORTAL_TEST_USERNAME = os.getenv("PORTAL_TEST_USERNAME", "test")

ADMIN_TEST_PASSWORD = os.getenv("ADMIN_TEST_PASSWORD", "macro123")
ADMIN_TEST_USERNAME = os.getenv("ADMIN_TEST_USERNAME", "admin")
